listen_address="127.0.0.1:4448"
sql_url=""

[sector_client]
endpoint="http://127.0.0.1:4449"

[contract_client]
endpoint="http://127.0.0.1:4450"

[journal_client]
endpoint="http://127.0.0.1:4452"

[bill_atomic_interval]
secs=10
nanos=0

[bill_retry_interval]
secs=2
nanos=0
