listen_address="127.0.0.1:4450"
sql_url=""

[account_client]
endpoint="http://127.0.0.1:4448"

[sector_client]
endpoint="http://127.0.0.1:4449"

[journal_client]
endpoint="http://127.0.0.1:4452"

[prepare_retry_interval]
secs=10
nanos=0

[prepare_atomic_interval]
secs=2
nanos=0


[apply_contract]
